<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-U079FS1" failures="1" tests="2" name="rahulshettyacademy.tests.ErrorValidationstest" time="7.594" errors="0" timestamp="2024-08-08T00:17:18 IST" skipped="1">
  <testcase classname="rahulshettyacademy.tests.ErrorValidationstest" name="LoginErrorValidations" time="5.278">
    <skipped/>
  </testcase> <!-- LoginErrorValidations -->
  <system-out/>
  <testcase classname="rahulshettyacademy.tests.ErrorValidationstest" name="LoginErrorValidations" time="2.316">
    <failure message="expected:&lt;Incorrect email or password.&gt; but was:&lt;Incorrect email  password.&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<Incorrect email or password.> but was:<Incorrect email  password.>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at rahulshettyacademy.tests.ErrorValidationstest.LoginErrorValidations(ErrorValidationstest.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- LoginErrorValidations -->
  <system-out/>
</testsuite> <!-- rahulshettyacademy.tests.ErrorValidationstest -->
